//! Host-side bindings for the `tak:plugin@0.1.0` WIT.
//!
//! Generated by `wasmtime::component::bindgen!` against
//! `crates/tak-plugin-api/wit/firehose.wit`. The macro produces a
//! `TakPlugin` host type that owns a typed entry point per
//! exported interface, plus traits for the imported interfaces
//! (`log`, `clock`) the host implements.

#![allow(missing_docs, missing_debug_implementations)] // macro-generated
#![allow(clippy::unwrap_used)] // macro internals

wasmtime::component::bindgen!({
    path: "../tak-plugin-api/wit",
    world: "tak-plugin",
    // wasmtime 44 default is sync; async is opt-in via a separate
    // generation flag we don't need yet.
    ownership: Owning,
});

pub(crate) use exports::tak::plugin::inbound;
pub(crate) use tak::plugin::{clock, log};
